<?php
namespace Customize\Repository\Master;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Customize\Entity\Master\BusinessStatus;
use Eccube\Repository\AbstractRepository;

/**
 * BusinessStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessStatusRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, BusinessStatus::class);
    }


}
