<?php
namespace Customize\Repository\Master;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Customize\Entity\Master\InvoiceAddItems;
use Eccube\Repository\AbstractRepository;

/**
 * InvoiceAddItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceAddItemsRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, InvoiceAddItems::class);
    }


}
