<?php
namespace Customize\Repository\Master;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Customize\Entity\Master\Kind;
use Eccube\Repository\AbstractRepository;

/**
 * KindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KindRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Kind::class);
    }
}
