<?php
namespace Customize\Repository\Master;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Customize\Entity\Master\WorkDetails;
use Eccube\Repository\AbstractRepository;

/**
 * WorkDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkDetailsRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, WorkDetails::class);
    }


}
