<?php

namespace Customize\Repository;

use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use Eccube\Doctrine\Query\Queries;
use Customize\Entity\BusinessPlan;
use Eccube\Util\StringUtil;
//use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * BusinessPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessPlanRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * BusinessPlanRepository constructop.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     */
    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, BusinessPlan::class);
        $this->queries = $queries;
    }

    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('bp');
        // Customer
        if ( isset($searchData['contractor_id']) ) {
            $qb
                ->andWhere("bp.contractor_id = :contractor_id")
                ->setParameter('contractor_id', $searchData['contractor_id']);
        }

        $qb
            ->orderBy('bp.kind_id', 'ASC')
            ->addOrderBy('bp.id', 'DESC');

        //return $this->queries->customize(QueryKey::PAYSLIP_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    public function getActivePlan($searchData)
    {
        $qb = $this->createQueryBuilder('bp');
        if ( isset($searchData['contractor_id']) ) {
            $qb
                ->andWhere("bp.contractor_id = :contractor_id")
                ->setParameter('contractor_id', $searchData['contractor_id']);
        }
        if ( isset($searchData['kind_id']) ) {
            $qb
                ->andWhere("bp.kind_id = :kind_id")
                ->setParameter('kind_id', $searchData['kind_id']);
        }

        $qb
            ->andWhere("bp.period_start <= :now")
            ->andWhere("bp.period_end IS NULL or bp.period_end >= :now")
            ->setParameter('now', new \Datetime())
            ->orderBy('bp.period_end', 'ASC')
            ->addOrderBy('bp.id', 'DESC');

//echo $qb->getQuery()->getSQL();
        //return $this->queries->customize(QueryKey::PAYSLIP_SEARCH, $qb, $searchData);
        //return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
        return $qb->getQuery()->getSingleResult();
    }

    /**
     * Get query key
     *
     * @return string
     */
    public function getQueryKey()
    {
        return 'BusinessPlan.getQueryBuilderBySearchData';
    }

}
