<?php
namespace Customize\Repository;

use Customize\Entity\Business;
use Customize\Entity\BusinessStaff;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\Master\BusinessStatus;
use Eccube\Entity\Master\Pref;
use Eccube\Entity\Master\Sex;
use Eccube\Util\StringUtil;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;

/**
 * BusinessStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessStaffRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManager;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    public const COLUMNS = [
        'business_id' => 'bs.id', 'name' => 'bs.name01',
    ];

    /**
     * BusinessStaffRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     * @param EntityManagerInterface $entityManager
     * @param EccubeConfig $eccubeConfig
     */
    public function __construct(
        RegistryInterface $registry,
        Queries $queries,
        EntityManagerInterface $entityManager,
        EccubeConfig $eccubeConfig
    ) {
        parent::__construct($registry, BusinessStaff::class);

        $this->queries = $queries;
        $this->entityManager = $entityManager;
        $this->eccubeConfig = $eccubeConfig;
    }

    /**
     * @return QueryBuilder
     */
    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('bs');

        // name
        if ( isset($searchData['name']) && StringUtil::isNotBlank($searchData['name']) ) {
            $qb
                ->andWhere('bs.name = :name OR bs.name LIKE :likeName')
                ->setParameter('name', $searchData['name'])
                ->setParameter('likeName', '%'.$searchData['name'].'%');
        }

        $qb
            ->orderBy('bs.id', 'DESC');

   //echo $qb->getQuery()->getSQL();

        //return $this->queries->customize(QueryKey::CUSTOMER_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /**
    * @return getQueryBuilderByBusinessID
    */
    public function getQueryBuilderByBusinessID($Business)
    {
        $qb = $this->createQueryBuilder('bs');

        $qb
            ->andWhere('bs.Business = :business')
            ->setParameter('business', $Business);
        $qb
            ->orderBy('bs.id', 'DESC');

   //echo $qb->getQuery()->getSQL();

        //return $this->queries->customize(QueryKey::CUSTOMER_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $Business);
    }

    public function getBusinessStaffByThisMonth($searchData)
    {
        $qb = $this->createQueryBuilder('bs');
        $qb->where('bs.visible = true');

        // Staff
        if ( isset($searchData['Staff']) && StringUtil::isNotBlank($searchData['Staff']) ) {
            $qb
                ->andWhere("bs.Staff = :staff")
                ->setParameter('staff', $searchData['Staff']);
        }
        if ( isset($searchData['Customer']) && StringUtil::isNotBlank($searchData['Customer']) ) {
            $qb
                ->innerJoin('Customize\Entity\Business', 'b', 'WITH', 'b.id = bs.Business')
                ->andWhere("b.Customer = :customer")
                ->setParameter('customer', $searchData['Customer']);
        }
        // working_ym
        if ( isset($searchData['working_ym']) ) {
            $qb
                ->andWhere("bs.period_start <= :working_ym")
                ->andWhere("bs.period_end is NULL OR bs.period_end >= :working_ym")
                ->setParameter('working_ym', date('Y-m-d', strtotime('first day of ' . $searchData['working_ym'])) );
        }

        $qb->orderBy('bs.id', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * Get query key
     *
     * @return string
     */
    public function getQueryKey()
    {
        return 'Config.getQueryBuilderBySearchData';
    }

}
