<?php
namespace Customize\Repository;

use Customize\Entity\Business;
use Customize\Entity\BusinessStaff;
use Customize\Entity\BusinessStaffWorkingTime;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\Master\BusinessStatus;
use Eccube\Entity\Master\Pref;
use Eccube\Entity\Master\Sex;
use Eccube\Util\StringUtil;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;

/**
 * BusinessStaffWorkingTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessStaffWorkingTimeRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManager;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    /**
     * BusinessStaffWorkingTimeRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     * @param EntityManagerInterface $entityManager
     * @param EccubeConfig $eccubeConfig
     */
    public function __construct(
        RegistryInterface $registry,
        Queries $queries,
        EntityManagerInterface $entityManager,
        EccubeConfig $eccubeConfig
    ) {
        parent::__construct($registry, BusinessStaffWorkingTime::class);

        $this->queries = $queries;
        $this->entityManager = $entityManager;
        $this->eccubeConfig = $eccubeConfig;
    }

    /**
     * @return QueryBuilder
     */
    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('b');

        // name
        if ( isset($searchData['name']) && StringUtil::isNotBlank($searchData['name']) ) {
            $qb
                ->andWhere('b.name = :name OR b.name LIKE :likeName')
                ->setParameter('name', $searchData['name'])
                ->setParameter('likeName', '%'.$searchData['name'].'%');
        }

        $qb
            ->orderBy('b.id', 'DESC');

   //echo $qb->getQuery()->getSQL();

        //return $this->queries->customize(QueryKey::CUSTOMER_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /**
    * @return getQueryBuilderByBusinessID
    */
    public function getQueryBuilderByBusinessID($Business)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->andWhere('b.Business = :business')
            ->setParameter('business', $Business);
        $qb
            ->orderBy('b.id', 'DESC');

   //echo $qb->getQuery()->getSQL();

        //return $this->queries->customize(QueryKey::CUSTOMER_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $Business);
    }

    /**
     * Get query key
     *
     * @return string
     */
    public function getQueryKey()
    {
        return 'Config.getQueryBuilderBySearchData';
    }

}
