<?php

namespace Customize\Repository;

use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use Eccube\Doctrine\Query\Queries;
use Customize\Entity\Invoice;
use Eccube\Util\StringUtil;
//use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * InvoiceRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     */
    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, Invoice::class);
        $this->queries = $queries;
    }

    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('i');

        // Customer
        if ( isset($searchData['Customer']) && StringUtil::isNotBlank($searchData['Customer']) ) {
            $qb
                ->andWhere("i.Customer = :customer")
                ->setParameter('customer', $searchData['Customer']);
        }
        // issue_ym
        if ( isset($searchData['issue_ym']) ) {
            $qb
                ->andWhere("i.issue_ym >= :issue_ym_s")
                ->setParameter('issue_ym_s', $searchData['issue_ym']->format('Y-m-d'));

            $issue_ym = $searchData['issue_ym'];
            $issue_ym->modify('+1 month');

            $qb
                ->andWhere("i.issue_ym < :issue_ym_e")
                ->setParameter('issue_ym_e', $issue_ym->format('Y-m-d'));
        }

        $qb
            ->orderBy('i.id', 'DESC');

        //return $this->queries->customize(QueryKey::INVOICE_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /**
     * Get query key
     *
     * @return string
     */
    public function getQueryKey()
    {
        return 'Invoice.getQueryBuilderBySearchData';
    }

}
