<?php

namespace Customize\Repository;

use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use Eccube\Doctrine\Query\Queries;
use Customize\Entity\InvoiceIssued;
use Eccube\Util\StringUtil;
//use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;

/**
 * InvoiceIssuedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceIssuedRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * InvoiceIssuedRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     */
    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, InvoiceIssued::class);
        $this->queries = $queries;
    }

    /*
     * 請求一覧
     * invoice_issued に存在する
     * report に存在しないにするか検討？？？
     */
    public function getQueryBuilderByIssuedData($searchData)
    {
        $qb = $this->createQueryBuilder('ii');

        // Customer
        if ( isset($searchData['Customer']) && StringUtil::isNotBlank($searchData['Customer']) ) {
            $qb->andWhere("ii.Customer = :customer")
                ->setParameter('customer', $searchData['Customer']);
        }
        // issue_ym
        if ( isset($searchData['issue_ym']) ) {
            $qb
                ->andWhere("ii.issue_ym >= :issue_ym_s")
                ->setParameter('issue_ym_s', $searchData['issue_ym']->format('Y-m-d'));

            $issue_ym = $searchData['issue_ym'];
            $issue_ym->modify('+1 month');

            $qb->andWhere("ii.issue_ym < :issue_ym_e")
                ->setParameter('issue_ym_e', $issue_ym->format('Y-m-d'));
        }
        $qb->orderBy('ii.Customer');

//echo $qb->getQuery()->getSQL();
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /*
     * 請求再発行
     * invoice_issued に存在する
     * report に status=null が存在する
     */
    public function getQueryBuilderByReIssueData($searchData)
    {
        $qb = $this->createQueryBuilder('ii');

        $qb->leftJoin('Customize\Entity\Report', 'r', 'WITH', 'ii.Customer = r.Customer')
            ->where('r.issue_status IS NULL');

        // 発行年月を設定
        if ( isset($searchData['working_ym']) ) {
            $working_ym_s = date('Y-m-d', strtotime('first day of ' . $searchData['working_ym']));
            $working_ym_e = date('Y-m-d', strtotime('last day of ' . $searchData['working_ym']));
            $qb
                ->andWhere("ii.issue_ym >= :working_ym_s")
                ->andWhere("ii.issue_ym <= :working_ym_e")
                ->andWhere("r.working_day >= :working_ym_s")
                ->andWhere("r.working_day <= :working_ym_e")
                ->setParameter('working_ym_s', $working_ym_s)
                ->setParameter('working_ym_e', $working_ym_e);
        }
        $qb->groupBy('ii.Customer');
        $qb->orderBy('ii.Customer');

        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /**
     * Get query key
     *
     * @return string
     */
    public function getQueryKey()
    {
        return 'Invoice.getQueryBuilderByIssuedData';
    }

}
