<?php
namespace Customize\Repository;

use Customize\Entity\MainBank;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Eccube\Util\StringUtil;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;

/**
 * MainBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainBankRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManager;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    public const COLUMNS = [
        'main_bank_id' => 'c.id', 'name' => 'c.name01',
    ];

    /**
     * MainBankRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     * @param EntityManagerInterface $entityManager
     * @param EccubeConfig $eccubeConfig
     */
    public function __construct(
        RegistryInterface $registry,
        Queries $queries,
        EntityManagerInterface $entityManager,
        EccubeConfig $eccubeConfig
    ) {
        parent::__construct($registry, MainBank::class);

        $this->queries = $queries;
        $this->entityManager = $entityManager;
        $this->eccubeConfig = $eccubeConfig;
    }

    public function newMainBank()
    {
        $MainBank = new \Customize\Entity\MainBank();

        return $MainBank;
    }

    /**
     * @param array{
     *         multi?:string,
     *         sortkey?:string,
     *         sorttype?:string
     *     } $searchData
     * @return QueryBuilder
     */
    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->orderBy('m.id', 'DESC');

   //echo $qb->getQuery()->getSQL();

        //return $this->queries->customize(QueryKey::CUSTOMER_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /**
     * Get query key
     *
     * @return string
     */
    public function getQueryKey()
    {
        return 'MainBank.getQueryBuilderBySearchData';
    }

}
