<?php
namespace Customize\Repository;

use Customize\Entity\Master\MyStatus;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\Customer;
use Eccube\Entity\Master\Pref;
use Eccube\Entity\Master\Sex;
use Eccube\Util\StringUtil;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;

/**
 * MyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManager;

    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    public const COLUMNS = [
        'my_id' => 'c.id', 'name' => 'c.name01',
    ];

    /**
     * MyRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     * @param EntityManagerInterface $entityManager
     * @param EccubeConfig $eccubeConfig
     */
    public function __construct(
        RegistryInterface $registry,
        Queries $queries,
        EntityManagerInterface $entityManager,
        EccubeConfig $eccubeConfig
    ) {
        parent::__construct($registry, My::class);

        $this->queries = $queries;
        $this->entityManager = $entityManager;
        $this->eccubeConfig = $eccubeConfig;
    }

    public function newMy()
    {
//        $MyStatus = $this->getEntityManager()
//            ->findAll(MyStatus::class, MyStatus::STATE);

        $My = new \Customize\Entity\My();
//        $My
//            ->setStatus($MyStatus)
//            ->setSecretKey($this->getUniqueSecretKey());
//            ->setPoint(0);

        return $My;
    }

    /**
     * @param array{
     *         multi?:string,
     *         pref?:Pref,
     *         sex?:Sex[],
     *         birth_month?:string|int,
     *         birth_start?:\DateTime,
     *         birth_end?:\DateTime,
     *         phone_number?:string,
     *         buy_total_start?:string|int,
     *         buy_total_end?:string|int,
     *         buy_times_start?:string|int,
     *         buy_times_end?:string|int,
     *         create_datetime_start?:\DateTime,
     *         create_datetime_end?:\DateTime,
     *         create_date_start?:\DateTime,
     *         create_date_end?:\DateTime,
     *         update_datetime_start?:\DateTime,
     *         update_datetime_end?:\DateTime,
     *         update_date_start?:\DateTime,
     *         update_date_end?:\DateTime,
     *         last_buy_datetime_start?:\DateTime,
     *         last_buy_datetime_end?:\DateTime,
     *         last_buy_start?:\DateTime,
     *         last_buy_end?:\DateTime,
     *         my_status?:MyStatus[],
     *         buy_product_name?:string,
     *         sortkey?:string,
     *         sorttype?:string
     *     } $searchData
     * @return QueryBuilder
     */
    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('s');

        // name
        if ( isset($searchData['name']) && StringUtil::isNotBlank($searchData['name']) ) {
            $clean_name = preg_replace('/\s+|[　]+/u', '', $searchData['name']);
            $qb
                ->andWhere('CONCAT(s.name01, s.name02) LIKE :name')
                ->setParameter('name', '%'.$clean_name.'%');
        }
        // status
        if (!empty($searchData['status']) && count($searchData['status'])) {
            $qb
                ->andWhere($qb->expr()->in('s.Status', ':statuses'))
                ->setParameter('statuses', $searchData['status']);
        }

        $qb
            ->orderBy('s.id', 'DESC');

        return $this->queries->customize(QueryKey::CUSTOMER_SEARCH, $qb, $searchData);
    }

    /**
     * ユニークなシークレットキーを返す.
     *
     * @return string
     */
    public function getUniqueSecretKey()
    {
        do {
            $key = StringUtil::random(32);
            $My = $this->findOneBy(['secret_key' => $key]);
        } while ($My);

        return $key;
    }

    /**
     * ユニークなパスワードリセットキーを返す
     *
     * @return string
     */
    public function getUniqueResetKey()
    {
        do {
            $key = StringUtil::random(32);
            $My = $this->findOneBy(['reset_key' => $key]);
        } while ($My);

        return $key;
    }

    /**
     * 仮会員をシークレットキーで検索する.
     *
     * @param $secretKey
     *
     * @return My|null 見つからない場合はnullを返す.
     */
    public function getProvisionalMyBySecretKey($secretKey)
    {
        return $this->findOneBy([
            'secret_key' => $secretKey,
            'Status' => MyStatus::PROVISIONAL,
        ]);
    }

    /**
     * 本会員をemailで検索する.
     *
     * @param $email
     *
     * @return My|null 見つからない場合はnullを返す.
     */
    public function getRegularMyByEmail($email)
    {
        return $this->findOneBy([
            'email' => $email,
            'Status' => MyStatus::REGULAR,
        ]);
    }

    /**
     * 本会員をリセットキー、またはリセットキーとメールアドレスで検索する.
     *
     * @param $resetKey
     * @param $email
     *
     * @return My|null 見つからない場合はnullを返す.
     */
    public function getRegularMyByResetKey($resetKey, $email = null)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.reset_key = :reset_key AND c.Status = :status AND c.reset_expire >= :reset_expire')
            ->setParameter('reset_key', $resetKey)
            ->setParameter('status', MyStatus::REGULAR)
            ->setParameter('reset_expire', new \DateTime());

        if ($email) {
            $qb
                ->andWhere('c.email = :email')
                ->setParameter('email', $email);
        }

        return $qb->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * リセット用パスワードを生成する.
     *
     * @return string
     */
    public function getResetPassword()
    {
        return StringUtil::random(8);
    }

    /**
     * 仮会員, 本会員の会員を返す.
     * Eccube\Entity\MyのUniqueEntityバリデーションで使用しています.
     *
     * @param array $criteria
     *
     * @return My[]
     */
    public function getNonWithdrawingMys(array $criteria = [])
    {
        $criteria['Status'] = [
            MyStatus::PROVISIONAL,
            MyStatus::REGULAR,
        ];

        return $this->findBy($criteria);
    }
}
