<?php

namespace Customize\Repository;

use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use Eccube\Doctrine\Query\Queries;
use Customize\Entity\Payslip;
use Eccube\Util\StringUtil;
//use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * PayslipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayslipRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * PayslipRepository constructop.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     */
    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, Payslip::class);
        $this->queries = $queries;
    }

    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('p');

        // Staff
        if ( isset($searchData['Staff']) && StringUtil::isNotBlank($searchData['Staff']) ) {
            $qb
                ->andWhere("p.Staff = :staff")
                ->setParameter('staff', $searchData['Staff']);
        }
        // issue_ym
        if ( isset($searchData['issue_ym']) ) {
            $qb
                ->andWhere("p.issue_ym >= :issue_ym_s")
                ->setParameter('issue_ym_s', $searchData['issue_ym']->format('Y-m-d'));

            $issue_ym = $searchData['issue_ym'];
            $issue_ym->modify('+1 month');

            $qb
                ->andWhere("p.issue_ym <= :issue_ym_e")
                ->setParameter('issue_ym_e', $issue_ym->format('Y-m-d'));
        }

        $qb
            ->orderBy('p.id', 'DESC');

        //return $this->queries->customize(QueryKey::PAYSLIP_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /**
     * Get query key
     *
     * @return string
     */
    public function getQueryKey()
    {
        return 'Payslip.getQueryBuilderBySearchData';
    }

}
