<?php

namespace Customize\Repository;

use Customize\Entity\Staff;
use Customize\Entity\Report;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\Customer;
use Eccube\Util\StringUtil;
//use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * ReportRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     */
    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, Report::class);
        $this->queries = $queries;
    }

    public function getQueryBuilderBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('r');

        $qb->where('r.visible = true');

        // Staff
        if ( isset($searchData['Staff']) && StringUtil::isNotBlank($searchData['Staff']) ) {
            $qb
                ->andWhere("r.Staff = :staff")
                ->setParameter('staff', $searchData['Staff']);
        }
        // Customer
        if ( isset($searchData['Customer']) ) {
            $qb
                ->andWhere("r.Customer = :customer")
                ->setParameter('customer', $searchData['Customer']);
        }
        // working_ym
        if ( isset($searchData['working_ym']) ) {
            $qb
                ->andWhere("r.working_day >= :working_ym_s")
                ->setParameter('working_ym_s', $searchData['working_ym']->format('Y-m-d'));

            $searchData['working_ym'] = $searchData['working_ym'];
            $searchData['working_ym']->modify('+1 month');

            $qb
                ->andWhere("r.working_day < :working_ym_e")
                ->setParameter('working_ym_e', $searchData['working_ym']->format('Y-m-d'));
        }

        if ( isset($searchData['sortkey']) && $searchData['sortkey'] == 'customer_id' ) {
            $sortType = ( isset($searchData['sorttype']) && $searchData['sorttype'] == 'a' ) ? 'ASC' : 'DESC';
            $qb
                ->orderBy('r.Customer', $sortType)
                ->addOrderBy('r.working_day', 'DESC')
                ;
        }else{
            $qb
                ->orderBy('r.working_day', 'DESC');
        }

//echo $qb->getQuery()->getSQL();

        //return $this->queries->customize(QueryKey::REPORT_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /*
     * 請求暑発行
     * invoice_issued に存在しない
     * report に存在する
     */
     public function getQueryBuilderByIssueList($searchData)
     {
         $qb = $this->createQueryBuilder('r');

         $qb->leftJoin('Customize\Entity\InvoiceIssued', 'ii', 'WITH', 'ii.Customer = r.Customer')
             ->where('ii.Customer IS NULL');

         if ( isset($searchData['working_ym']) ) {
             $working_ym_s = date('Y-m-d', strtotime('first day of ' . $searchData['working_ym']));
             $working_ym_e = date('Y-m-d', strtotime('last day of ' . $searchData['working_ym']));
             $qb
                 ->andWhere("r.working_day >= :working_ym_s")
                 ->andWhere("r.working_day <= :working_ym_e")
                 ->setParameter('working_ym_s', $working_ym_s)
                 ->setParameter('working_ym_e', $working_ym_e);
         }

         $qb->groupBy('r.Customer');
         $qb->orderBy('r.Customer');

//         echo $qb->getQuery()->getSQL();
//         exit;

         return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
     }

    /*
     * 請求暑発行
     * invoice_issued に存在しない
     * report に存在する
     */
    public function getQueryBuilderByIssueData($searchData)
    {
        $qb = $this->createQueryBuilder('r');
//        $qb->select('r.id, r.working_day, r.working_time_start, r.working_time_end');
        $qb->select('r.Customer');
//        $qb->leftJoin('Customize\Entity\InvoiceIssued', 'ii', 'WITH', 'ii.Customer = r.Customer')
//            ->where('ii.Customer IS NULL');
        // working_ym
/*
        if ( isset($searchData['working_ym']) ) {
            $working_ym_s = date('Y-m-d', strtotime('first day of ' . $searchData['working_ym']));
            $working_ym_e = date('Y-m-d', strtotime('last day of ' . $searchData['working_ym']));
            $qb
                ->andWhere("r.working_day >= :working_ym_s")
                ->andWhere("r.working_day <= :working_ym_e")
                ->setParameter('working_ym_s', $working_ym_s)
                ->setParameter('working_ym_e', $working_ym_e);
        }
*/
//        $qb->groupBy('r.Customer, r.id, r.working_day, r.working_time_start, r.working_time_end');
        $qb->groupBy('r.Customer');
        $qb->orderBy('r.Customer');

    //        $qb->groupBy('r.Customer');
    //        $qb->orderBy('r.Customer.id', 'DESC');

/*
        $qb->leftJoin('Customize\Entity\InvoiceIssued', 'ii')
            ->where('r.Customer = ii.Customer')
            ->andWhere('ii.Customer IS NULL');
*/
/*
SELECT r.customer_id, ii.customer_id FROM dtb_report r left JOIN dtb_invoice_issued ii ON r.customer_id = ii.customer_id
WHERE r.working_day >= '2025-08-01' AND r.working_day <= '2025-08-31'
AND ii.customer_id IS NULL
group by r.customer_id
order by r.customer_id;
*/

//        $qb->ightJoin('Customize\Entity\Report', 'r', 'WITH', 'r.Customer = ii.Customer')
//            ->andWhere('ii.Customer IS NULL');

echo $qb->getQuery()->getSQL();
exit;
        //return $this->queries->customize(QueryKey::INVOICE_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /*
     *
     */
    public function getQueryBuilderForPaySlipBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->select('IDENTITY(r.Staff) as staff_id, count(r.Staff) as cnt')
            ->addSelect('CONCAT(s.name01, \' \', s.name02) as staff_name')
            ->innerJoin('Customize\Entity\Staff', 's', 'WITH', 's.id = r.Staff')
            ;

        $qb->where('r.visible = true');

        // Staff
        if ( isset($searchData['Staff']) && StringUtil::isNotBlank($searchData['Staff']) ) {
            $qb
                ->andWhere("r.Staff = :staff")
                ->setParameter('staff', $searchData['Staff']);
        }
        // Customer
        if ( isset($searchData['Customer']) ) {
            $qb
                ->andWhere("r.Customer = :customer")
                ->setParameter('customer', $searchData['Customer']);
        }
        // working_ym
        if ( isset($searchData['working_ym']) ) {
            $qb
                ->andWhere("r.working_day >= :working_ym_s")
                ->setParameter('working_ym_s', $searchData['working_ym']->format('Y-m-d'));

            $searchData['working_ym'] = $searchData['working_ym'];
            $searchData['working_ym']->modify('+1 month');

            $qb
                ->andWhere("r.working_day < :working_ym_e")
                ->setParameter('working_ym_e', $searchData['working_ym']->format('Y-m-d'));
        }

        $qb->groupBy('r.Staff');

        //return $this->queries->customize(QueryKey::REPORT_SEARCH, $qb, $searchData);
        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /*
     *
     */
    public function getQueryBuilderForInvoiceBySearchData($searchData)
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->select('IDENTITY(r.Customer) as customer_id, count(r.Customer) as cnt')
            ->addSelect('CONCAT(c.name01, \' \', c.name02) as customer_name')
            ->innerJoin('Eccube\Entity\Customer', 'c', 'WITH', 'c.id = r.Customer')
            ;

        $qb->where('r.visible = true');

        // Customer
        if ( isset($searchData['Staff']) && StringUtil::isNotBlank($searchData['Staff']) ) {
            $qb
                ->andWhere("r.Staff = :staff")
                ->setParameter('staff', $searchData['Staff']);
        }
        // Customer
        if ( isset($searchData['Customer']) && StringUtil::isNotBlank($searchData['Customer']) ) {
            $qb
                ->andWhere("r.Customer = :customer")
                ->setParameter('customer', $searchData['Customer']);
        }
        // working_ym
        if ( isset($searchData['working_ym']) ) {
            $working_ym_s = date('Y-m-d', strtotime('first day of ' . $searchData['working_ym']));
            $working_ym_e = date('Y-m-d', strtotime('last day of ' . $searchData['working_ym']));
            $qb
                ->andWhere("r.working_day >= :working_ym_s")
                ->setParameter('working_ym_s', $working_ym_s);

            $qb
                ->andWhere("r.working_day <= :working_ym_e")
                ->setParameter('working_ym_e', $working_ym_e);
        }
        // issue_status
        if ( isset($searchData['issue_status']) ) {
            if ( $searchData['issue_status'] == 'NULL' ) {
                $qb
                    ->andWhere("r.issue_status IS NULL");
            }else{
                $qb
                    ->andWhere("r.issue_status = :issue_status")
                    ->setParameter('issue_status', $searchData['issue_status']);
            }
        }
        $qb->groupBy('r.Customer');

        return $this->queries->customize($this->getQueryKey(), $qb, $searchData);
    }

    /*
     *
     */
    public function getMonthlyReportByStaff($searchData)
    {

        $qb = $this->createQueryBuilder('r');
        $qb->where('r.visible = true');

        // Staff
        if ( isset($searchData['Staff']) && StringUtil::isNotBlank($searchData['Staff']) ) {
            $qb
                ->andWhere("r.Staff = :staff")
                ->setParameter('staff', $searchData['Staff']);
        }
        // working_ym
        if ( isset($searchData['working_ym']) ) {
            $qb
                ->andWhere("r.working_day >= :working_ym_s")
                ->setParameter('working_ym_s', date('Y-m-d', strtotime('first day of ' . $searchData['working_ym'])));
            $qb
                ->andWhere("r.working_day < :working_ym_e")
                ->setParameter('working_ym_e', date('Y-m-d', strtotime('last day of ' . $searchData['working_ym'])) );
        }

        $qb->orderBy('r.working_day', 'ASC');


        return $qb->getQuery()->getResult();
    }

    /*
     *
     */
    public function getMonthlyReportByCustomer($searchData)
    {

        $qb = $this->createQueryBuilder('r');
        $qb->where('r.visible = true');

        // Customer
        if ( isset($searchData['Customer']) && StringUtil::isNotBlank($searchData['Customer']) ) {
            $qb
                ->andWhere("r.Customer = :customer")
                ->setParameter('customer', $searchData['Customer']);
        }
        // working_ym
        if ( isset($searchData['working_ym']) ) {
            $qb
                ->andWhere("r.working_day >= :working_ym_s")
                ->setParameter('working_ym_s', date('Y-m-d', strtotime('first day of ' . $searchData['working_ym'])));
            $qb
                ->andWhere("r.working_day < :working_ym_e")
                ->setParameter('working_ym_e', date('Y-m-d', strtotime('last day of ' . $searchData['working_ym'])) );
        }

        $qb->orderBy('r.working_day', 'ASC');


        return $qb->getQuery()->getResult();
    }

    /*
     *
     */
    public function setIssueMonthlyReportByCustomer($searchData){

        $this->createQueryBuilder('r')
                ->update()
                ->set('r.issue_status', 1)
                ->where("r.Customer = :customer")
                ->andWhere("r.working_day >= :working_ym_s")
                ->andWhere("r.working_day < :working_ym_e")
                ->setParameter('customer', $searchData['Customer'])
                ->setParameter('working_ym_s', date('Y-m-d', strtotime('first day of ' . $searchData['working_ym'])))
                ->setParameter('working_ym_e', date('Y-m-d', strtotime('last day of ' . $searchData['working_ym'])))
                ->getQuery()
                ->execute();

        return;
    }

    /**
     * Get query key
     *
     * @return string
     */
    public function getQueryKey()
    {
        return 'Report.getQueryBuilderBySearchData';
    }

}
